import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[colors.primary]
background = "0x242839"
foreground = "0x2E6F4F"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "Hack"
style = "Medium"

[font.italic]
family = "Hack"
style = "Light Italic"

[font.normal]
family = "Hack"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10
